var data =[
    //凉菜
    {
        "id":0,
        "name":"泡椒凤爪",
        "price":20,
        "url":"img/small/l01.jpg",
        "Burl":"img/big/big-l01.jpg",
        "dis":"泡椒凤爪具有开胃生津、促进血液循环的功效,丰满洁白，咀嚼时骨肉生香，具有很强的催味功效。",
        "keywords":"凉菜，小吃，微辣",
        "isActive":false
    },
    {
        "id":1,
        "name":"拍黄瓜",
        "price":15,
        "url":"img/small/l02.jpg",
        "Burl":"img/big/big-l02.jpg",
        "dis":"在夏季的时候，人们总是喜欢吃一些清淡的，这样会更加的清凉爽口。拍黄瓜就是一道非常简单，也是非常爽口的一道家常凉菜，拍黄瓜经常出现在人们的餐桌上，在鱼肉的相称下，拍黄瓜是一道非常解腻爽口的凉菜。",
        "keywords":"凉菜",
        "isActive":false
    },
    {
        "id":2,
        "name":"柚子沙拉",
        "price":26,
        "url":"img/small/l03.jpg",
        "Burl":"img/big/big-l03.jpg",
        "dis":"柚子沙拉的原料本来是油炸鸡肉，但是为了突出健康的特点，本店只选择了烤制的豆腐，不含一滴油。还在里面加入了传统香料和罗望子酱，吃起来更加美味，营养专家和医生鼓励人们多吃柚子沙拉这样既有新鲜水果又有蔬菜的低脂肪、少盐、少糖的食物。",
        "keywords":"凉菜，甜品",
        "isActive":false
    },
    {
        "id":3,
        "name":"糖醋三丝",
        "price":16,
        "url":"img/small/l01.jpg",
        "Burl":"img/big/big-l01.jpg",
        "dis":"此菜荤素结合，搭配非常合理。成菜色彩好看，味道鲜美，色香味俱全",
        "keywords":"凉菜，酸甜可口",
        "isActive":false
    },
    {
        "id":4,
        "name":"琥珀花生",
        "price":10,
        "url":"img/small/l02.jpg",
        "Burl":"img/big/big-l02.jpg",
        "dis":"颗粒整齐饱满，裹糖均匀，无发沙现象，呈琥珀色，表面有光泽，甜酥，脆香，有浓郁的花生香味。",
        "keywords":"凉菜，小吃",
        "isActive":false
    },
    {
        "id":5,
        "name":"凉拌猪头肉",
        "price":50,
        "url":"img/small/l03.jpg",
        "Burl":"img/big/big-l03.jpg",
        "dis":"凉拌猪头肉不仅好吃，而且口感一流，肥而不腻，所以，吃货们都对这道凉拌猪头肉有着一种无法抵挡的感觉。",
        "keywords":"凉菜，微辣",
        "isActive":false
    },
    {
        "id":6,
        "name":"火山下雪",
        "price":20,
        "url":"img/small/l01.jpg",
        "Burl":"img/big/big-l01.jpg",
        "dis":"“火山下雪”是近年来新出现的一道菜名糖拌西红柿。因为西红柿是红色的像火，白糖是白色的像雪，所以叫火山下雪。",
        "keywords":"凉菜，甜品",
        "isActive":false
    },
    {
        "id":7,
        "name":"双椒拌皮蛋",
        "price":18,
        "url":"img/small/l02.jpg",
        "Burl":"img/big/big-l02.jpg",
        "dis":"皮蛋选用最好的松花皮蛋，这种皮蛋凉拌清爽可口，少量的凉拌食醋，味道更好。",
        "keywords":"凉菜，微辣",
        "isActive":false
    },
    {
        "id":8,
        "name":"风味脆黄喉",
        "price":40,
        "url":"img/small/l03.jpg",
        "Burl":"img/big/big-l03.jpg",
        "dis":" 说起黄喉，白色类似笋片一样，口感滑爽脆口。黄喉算是高蛋白低脂肪的营养食材之一，吃了不会胖哦！",
        "keywords":"凉菜，中辣",
        "isActive":false
    },

    //炖菜
    {
        "id":9,
        "name":"牛腩炖萝卜",
        "price":80,
        "url":"img/small/d01.jpg",
        "Burl":"img/big/big-d01.jpg",
        "dis":"“牛腩炖萝卜”是一道很受欢迎的滋补菜，白萝卜理气、促消化、排毒；牛肉更是养生的绝佳肉食，炖出来的牛肉质地软烂，醇香清鲜。味道香美，内含丰富营养。",
        "keywords":"热菜，炖菜，清淡，下火",
        "isActive":false
    },
    {
        "id":10,
        "name":"清炖猪蹄",
        "price":60,
        "url":"img/small/d02.jpg",
        "Burl":"img/big/big-d02.jpg",
        "dis":"猪蹄中含有较多的蛋白质、脂肪和碳水化合物，可加速新陈代谢，延缓机体衰老，并且对于哺乳期妇女能起到催乳和美容的双重作用，另外具通乳脉，滑肌肤、去寒热、托痈疽、发疮毒、抗老防癌之功效，特别适宜于经常四肢乏力、两腿抽筋、麻木、消化道出血、失血休克及缺血性脑病患者食之。",
        "keywords":"热菜，炖菜，清淡，肥而不腻",
        "isActive":false
    },
    {
        "id":11,
        "name":"菌菇炖乳鸽",
        "price":120,
        "url":"img/small/d03.jpg",
        "Burl":"img/big/big-d03.jpg",
        "dis":"鸽子营养价值较高， 对老年人、 体虚病弱、手术病人、孕妇及儿童非常适合。 鸽子的营养价值极高，既是名贵的美味佳肴，又是高级滋补佳品。鸽肉为高蛋白、低脂肪食品。蛋白含量为24.4%，超过兔、牛、猪、羊、鸡、鸭、鹅和狗等肉类，所含蛋白质中有许多人体的必需氨基酸，且消化吸收率在5%。鸽子肉的脂肪含量仅为0.3%，低于其他肉类，是人类理想的食品。",
        "keywords":"热菜，炖菜，hot",
        "isActive":false
    },
    {
        "id":12,
        "name":"鲫鱼炖粉条",
        "price":88,
        "url":"img/small/d01.jpg",
        "Burl":"img/big/big-d01.jpg",
        "dis":"鲫鱼肉质细嫩，肉营养价值很高，含有丰富的蛋白质、脂肪、钙、磷、铁等营养。鲫鱼性平味甘，入胃、肾，具有和中补虚、除羸、温胃进食、补中生气之功效。鲫鱼炖红薯粉条这道菜，味道鲜美，营养丰富。",
        "keywords":"热菜，炖菜，重辣",
        "isActive":false
    },
    {
        "id":13,
        "name":"双莲炖排骨",
        "price":80,
        "url":"img/small/d02.jpg",
        "Burl":"img/big/big-d02.jpg",
        "dis":"双莲炖排骨是一道美食，主原料有猪脆骨、莲藕、莲子，清香可口",
        "keywords":"热菜，炖菜",
        "isActive":false
    },
    {
        "id":14,
        "name":"莲藕炖仔鸭",
        "price":70,
        "url":"img/small/d03.jpg",
        "Burl":"img/big/big-d03.jpg",
        "dis":"莲藕生用性寒，有清热凉血作用，可用来治疗热性病症；莲藕味甘多液、对热病口渴、衄血、咯血、下血者尤为有益。",
        "keywords":"热菜，炖菜",
        "isActive":false
    },
    {
        "id":15,
        "name":"毛豆炖排骨",
        "price":76,
        "url":"img/small/d01.jpg",
        "Burl":"img/big/big-d01.jpg",
        "dis":"口味浓郁而不油腻，特别的下饭。就是在夏天，也是会大口大口的扒饭。",
        "keywords":"热菜，炖菜",
        "isActive":false
    },
    {
        "id":16,
        "name":"灵芝炖排骨",
        "price":200,
        "url":"img/small/d02.jpg",
        "Burl":"img/big/big-d02.jpg",
        "dis":"紫灵芝炖排骨是一道药膳汤，有健脾养肝的功效。原料有排骨，胡萝卜，莲藕，国琼紫灵芝片。",
        "keywords":"热菜，炖菜",
        "isActive":false
    },

    //烧菜
    {
        "id":17,
        "name":"红烧猪蹄",
        "price":66,
        "url":"img/small/s01.jpg",
        "Burl":"img/big/big-s01.jpg",
        "dis":"猪蹄营养丰富，味道可口。它不仅是家常菜肴，而且是滋补佳品。它里面还有丰富的胶原蛋白质，是一种廉价的美容食品。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":18,
        "name":"魔芋烧鸡翅",
        "price":55,
        "url":"img/small/s02.jpg",
        "Burl":"img/big/big-s02.jpg",
        "dis":"鸡翅油腻，吃多了容易发胖，加了魔芋结，正好能吸收油脂，还能产生饱腹感，减肥人士不二选择啊。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":19,
        "name":"锅烧肉",
        "price":68,
        "url":"img/small/s03.jpg",
        "Burl":"img/big/big-s03.jpg",
        "dis":"锅烧肉是一道汉族传统名菜，以猪肉为制作主料，锅烧肉的烹饪技巧以炸为主，口味属于咸鲜味。此菜色金黄，酥脆香可口。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":20,
        "name":"红烧肉",
        "price":36,
        "url":"img/small/s01.jpg",
        "Burl":"img/big/big-s01.jpg",
        "dis":"以五花肉为制作主料，红烧肉的烹饪技巧以砂锅为主，肥瘦相间，香甜松软，入口即化。红烧肉在我国各地流传甚广，是一道著名的大众菜肴。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":21,
        "name":"芋儿烧鸡",
        "price":56,
        "url":"img/small/s02.jpg",
        "Burl":"img/big/big-s02.jpg",
        "dis":"紫芋儿烧鸡是一道四川的汉族名菜。属于川菜家常菜之一，主要原料是鸡肉、辣椒，口味是麻辣，工艺是炒，鸡肉质地细嫩滑润，辣而不燥，芋儿粑糯回甜，让人吃过就忘不掉。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":22,
        "name":"板栗烧鸡",
        "price":86,
        "url":"img/small/s03.jpg",
        "Burl":"img/big/big-s03.jpg",
        "dis":"板栗淡淡的清香，搭配上软嫩多汁的鸡肉，一道色泽红亮、风味极佳的板栗烧鸡，是不是看着就会让你垂涎欲滴。！",
        "keywords":"热菜，烧菜",
        "isActive":false
    },
    {
        "id":23,
        "name":"东坡肘子",
        "price":76,
        "url":"img/small/s01.jpg",
        "Burl":"img/big/big-s01.jpg",
        "dis":"肘子的营养很丰富，含较多的蛋白质，特别是含有大量的胶原蛋白质，和肉皮一样，是使皮肤丰满、润泽，强体增肥的食疗佳品。猪肘，味甘、咸，性平；有和血脉、润肌肤、填肾精、健腰脚的作用。",
        "keywords":"热菜，烧菜,hot",
        "isActive":false
    },
    {
        "id":24,
        "name":"葱姜烧大虾",
        "price":120,
        "url":"img/small/s02.jpg",
        "Burl":"img/big/big-s02.jpg",
        "dis":"虾营养丰富，其肉质松软，易消化，对身体虚弱以及病后需要调养的人是极好的食物；虾中含有丰富的镁，能很好的保护心血管系统，它可减少血液中胆固醇含量，防止动脉硬化，同时还能扩张冠状动脉，有利于预防高血压及心肌梗死。",
        "keywords":"热菜，烧菜",
        "isActive":false
    },

    //热菜
    {
        "id":25,
        "name":"回锅肉",
        "price":25,
        "url":"img/small/r01.jpg",
        "Burl":"img/big/big-r01.jpg",
        "dis":"回锅肉的特点是：口味独特，色泽红亮，肥而不腻，入口浓香。回锅肉的特点是：口味独特，色泽红亮，肥而不腻，入口浓香。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":26,
        "name":"肉末茄子",
        "price":20,
        "url":"img/small/r02.jpg",
        "Burl":"img/big/big-r02.jpg",
        "dis":"此菜品为以茄子和猪肉为主要食材的汉族特色菜肴，起源于西汉，属于家常菜。营养丰富，色香味俱全。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":27,
        "name":"麻婆豆腐",
        "price":16,
        "url":"img/small/r03.jpg",
        "Burl":"img/big/big-r03.jpg",
        "dis":"麻婆豆腐外观色深红亮，红白绿相衬，豆腐形整不烂，吃起来具有麻、辣、烫、嫩、酥、香、鲜等风味，突出了川菜“麻辣”的特点。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":28,
        "name":"粉蒸牛肉",
        "price":50,
        "url":"img/small/r01.jpg",
        "Burl":"img/big/big-r01.jpg",
        "dis":"牛肉是中国人的第二大肉类食品，仅次于猪肉，牛肉蛋白质含量高，而脂肪含量低，所以味道鲜美，受人喜爱，享有“肉中骄子”的美称。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":29,
        "name":"鱼香肉丝",
        "price":18,
        "url":"img/small/r02.jpg",
        "Burl":"img/big/big-r02.jpg",
        "dis":"成菜色红润、肉嫩、质鲜、富鱼香味。其鱼香味并不来自鱼，而是由泡红辣椒、葱、姜、蒜、糖、盐、酱油等调味品调制而成。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":30,
        "name":"宫保鸡丁",
        "price":16,
        "url":"img/small/r03.jpg",
        "Burl":"img/big/big-r03.jpg",
        "dis":"宫保鸡丁选用鸡肉为主料，佐以花生米、黄瓜、辣椒等辅料烹制而成。 红而不辣、辣而不猛、香辣味浓、肉质滑脆。由于其入口鲜辣，鸡肉的鲜嫩配合花生的香脆。",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":31,
        "name":"清炒土豆丝",
        "price":12,
        "url":"img/small/r01.jpg",
        "Burl":"img/big/big-r01.jpg",
        "dis":"本味醇厚，咸鲜滑淡，质地细嫩，清淡平和，四季适宜",
        "keywords":"热菜",
        "isActive":false
    },
    {
        "id":32,
        "name":"芹菜肉丝",
        "price":18,
        "url":"img/small/r02.jpg",
        "Burl":"img/big/big-r02.jpg",
        "dis":"芹菜是常用蔬菜之一，既可热炒，又能凉拌，深受人们喜爱。旱芹含有丰富的维生素A、维生素B1、维生素B2、维生素C和维生素P，钙，铁，磷等矿物质含量也多，此外还有蛋白质、甘露醇和食物纤维等成分。",
        "keywords":"热菜",
        "isActive":false
    },
    //  饮品
    {
        "id":33,
        "name":"可口可乐",
        "price":15,
        "url":"img/small/y01.jpg",
        "Burl":"img/big/big-y01.jpg",
        "dis":"来一杯吧",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":34,
        "name":"果缤纷",
        "price":18,
        "url":"img/small/y02.jpg",
        "Burl":"img/big/big-y02.jpg",
        "dis":"来一杯吧",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":35,
        "name":"红茶",
        "price":10,
        "url":"img/small/y03.jpg",
        "Burl":"img/big/big-y03.jpg",
        "dis":"来一杯吧",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":36,
        "name":"法国红葡萄酒",
        "price":60,
        "url":"img/small/y01.jpg",
        "Burl":"img/big/big-y01.jpg",
        "dis":"精选爱尔兰红葡萄,味道纯正鲜美",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":37,
        "name":"德国白葡萄酒",
        "price":90,
        "url":"img/small/y02.jpg",
        "Burl":"img/big/big-y02.jpg",
        "dis":"精选意大利白葡萄,味道纯正鲜美",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":38,
        "name":"雪花啤酒",
        "price":20,
        "url":"img/small/y03.jpg",
        "Burl":"img/big/big-y03.jpg",
        "dis":"清凉的最佳饮品",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":39,
        "name":"哈威啤酒",
        "price":20,
        "url":"img/small/y01.jpg",
        "Burl":"img/big/big-y01.jpg",
        "dis":"来自哈城的大众饮品",
        "keywords":"饮品",
        "isActive":false
    },
    {
        "id":40,
        "name":"二锅头",
        "price":20,
        "url":"img/small/y02.jpg",
        "Burl":"img/big/big-y02.jpg",
        "dis":"喝了你就不想走",
        "keywords":"饮品",
        "isActive":false
    },


    //小吃
    {
        "id":41,
        "name":"陕西肉夹馍",
        "price":20,
        "url":"img/small/x01.jpg",
        "Burl":"img/big/big-x01.jpg",
        "dis":"陕西最有名的小吃",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":42,
        "name":"煎饼合子",
        "price":20,
        "url":"img/small/x02.jpg",
        "Burl":"img/big/big-x02.jpg",
        "dis":"煎饼中的queen",
        "keywords":"小吃",
        "isActive":false
    },

    {
        "id":43,
        "name":"驴肉火烧",
        "price":20,
        "url":"img/small/x03.jpg",
        "Burl":"img/big/big-x03.jpg",
        "dis":"河北最有名的小吃",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":44,
        "name":"太原拉面",
        "price":20,
        "url":"img/small/x01.jpg",
        "Burl":"img/big/big-x01.jpg",
        "dis":"山西最有名的小吃",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":45,
        "name":"过桥米线",
        "price":20,
        "url":"img/small/x02.jpg",
        "Burl":"img/big/big-x02.jpg",
        "dis":"云南最有名的小吃",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":46,
        "name":"印度飞饼",
        "price":20,
        "url":"img/small/x03.jpg",
        "Burl":"img/big/big-x03.jpg",
        "dis":"吃了你就不想走",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":47,
        "name":"担担面",
        "price":20,
        "url":"img/small/x01.jpg",
        "Burl":"img/big/big-x01.jpg",
        "dis":"是我们四川的名小吃",
        "keywords":"小吃",
        "isActive":false
    },
    {
        "id":48,
        "name":"双皮奶",
        "price":20,
        "url":"img/small/x02.jpg",
        "Burl":"img/big/big-x02.jpg",
        "dis":"广东的甜蜜小吃",
        "keywords":"小吃，甜品",
        "isActive":false
    },

    //  甜品

    {
        "id":49,
        "name":"布丁",
        "price":30,
        "url":"img/small/t01.jpg",
        "Burl":"img/big/big-t01.jpg",
        "dis":"没有吃过小布丁,就像没有谈过恋爱一样",
        "keywords":"甜品",
        "isActive":false
    },
    {
        "id":50,
        "name":"提拉米苏",
        "price":40,
        "url":"img/small/t02.jpg",
        "Burl":"img/big/big-t02.jpg",
        "dis":"提拉米苏的香甜 永远的味道",
        "keywords":"甜品",
        "isActive":false
    },
    {
        "id":51,
        "name":"杨枝甘露",
        "price":50,
        "url":"img/small/t03.jpg",
        "Burl":"img/big/big-t03.jpg",
        "dis":"香甜爽口的港式著名茶点",
        "keywords":"甜品",
        "isActive":false
    },
    {
        "id":52,
        "name":"芒果班戳",
        "price":20,
        "url":"img/small/t01.jpg",
        "Burl":"img/big/big-t01.jpg",
        "dis":"超高人气景点港式甜品",
        "keywords":"甜品,hot",
        "isActive":false
    },
    {
        "id":53,
        "name":"草莓大福",
        "price":20,
        "url":"img/small/t02.jpg",
        "Burl":"img/big/big-t02.jpg",
        "dis":"日式香滑清爽美食",
        "keywords":"甜品",
        "isActive":false
    },
    {
        "id":54,
        "name":"泡芙",
        "price":20,
        "url":"img/small/t03.jpg",
        "Burl":"img/big/big-t03.jpg",
        "dis":"西式甜品",
        "keywords":"甜品，小吃",
        "isActive":false
    },
    {
        "id":55,
        "name":"红豆西米露",
        "price":20,
        "url":"img/small/t01.jpg",
        "Burl":"img/big/big-t01.jpg",
        "dis":"东南亚国家的特产",
        "keywords":"甜品",
        "isActive":false
    },
    {
        "id":56,
        "name":"爱心蛋糕",
        "price":20,
        "url":"img/small/t02.jpg",
        "Burl":"img/big/big-t02.jpg",
        "dis":"只有更美 没有最美",
        "keywords":"甜品",
        "isActive":false
    }
];